apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=postgres;Port=5432;Database=fcg_users_db;Username=users;Password=userspw"
  Jwt__Key: "CHANGE-ME-VERY-LONG-SECRET-KEY-AT-LEAST-32-CHARS"
  RabbitMq__Password: guest
